User.delete_all

user_1 = User.create!(
  email: "admin@admin.com",
  password: "admin123",
  name: "Jean",
  age: 65,
  gender: "Homme",
  lifestyle: "Sédentaire",
  remote_work: true,
  address: "Avenue de Toulouse, 31270 Cugnaux",
  green_space: "Parc, jardin privé",
  household_size: 2,
  time_for_pet: "3h",
  daily_walk: true,
  pet_budget: 300,
  have_children: true,
  have_cat: true,
  have_dog: true,
  have_other_pets: true,
  description: "Je suis un homme de 65 ans, retraité, j'habite à Cugnaux. J'ai un chat, un chien et un lapin. J'ai 2 enfants et 3 petits-enfants. J'aime me promener dans le parc de la Ramée.",
  can_adopt_dog: true,
  can_adopt_cat: true,
  can_adopt_nac: true,
)

user_2 = User.create!(
  email: "marie@marie.com",
  password: "admin123",
  name: "Marie",
  age: 30,
  gender: "Femme",
  lifestyle: "Actif",
  remote_work: false,
  address: "Saint-Cyprien, Toulouse",
  green_space: "Parc, autre",
  household_size: 1,
  time_for_pet: "1h",
  daily_walk: true,
  pet_budget: 50,
  have_children: false,
  have_cat: false,
  have_dog: false,
  have_other_pets: false,
  description: "Je suis une femme de 30 ans, j'habite à Saint-Cyprien. J'aime me promener dans le parc Raymond IV. J'ai un appartement de 40m2.",
  can_adopt_dog: false,
  can_adopt_cat: true,
  can_adopt_nac: true,
)

user_3 = User.create!(
  email: "arthurdog@dog.fr",
  password: "admin123",
  name: "Arthur",
  age: 20,
  lifestyle: "Actif",
  remote_work: false,
  address: "Rue de la République, Toulouse",
  green_space: "Parc",
  household_size: 2,
  time_for_pet: "4h",
  daily_walk: true,
  pet_budget: 100,
  shelter_id: 1,
  have_children: false,
  have_cat: true,
  have_dog: false,
  have_other_pets: false,
  description: "Je suis un étudiant de 20 ans, j'habite à Toulouse. J'ai un chat. J'ai un appartement de 30m2.",
  can_adopt_dog: false,
  can_adopt_cat: true,
  can_adopt_nac: true,
)

user_4 = User.create!(
email: "justine@cat.fr",
password: "admin123",
name: "Justine",
age: 25,
lifestyle: "Sédentaire",
remote_work: true,
address: "Rue d'Encrabe, Plaisance du touch",
green_space: "Jardin privé, parc, autre",
household_size: 1,
time_for_pet: "2h",
daily_walk: true,
pet_budget: 500,
shelter_id: 2,
have_children: true,
have_cat: false,
have_dog: true,
have_other_pets: false,
description: "Je suis une femme de 25 ans, j'habite à Plaisance du touch. J'ai un chien. J'ai une maison de 100m2.",
can_adopt_dog: true,
can_adopt_cat: false,
can_adopt_nac: true,
)

user_5 = User.create!(
email: "christophe@nac.com",
password: "admin123",
name: "Christophe",
age: 40,
lifestyle: "Actif",
remote_work: false,
address: "Rue de la République, Toulouse",
green_space: "Parc",
household_size: 1,
time_for_pet: "1h",
daily_walk: false,
pet_budget: 25,
have_children: true,
have_cat: false,
have_dog: false,
have_nac: false,
description: "Je suis un homme de 40 ans, j'habite à Toulouse. J'ai 2 enfants. J'ai un appartement de 50m2.",
can_adopt_dog: false,
can_adopt_cat: false,
can_adopt_nac: false,
)
